"use client";
import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Header, About, Signature } from "../components";
import { BackgroundMap } from "~/components/BackgroundMap";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div id="app" className="w-100 h-screen">
            <div className=" w-100 zi100">
              <Header />
            </div>
            <div id="map" className="mapContainer w-100 fixed">
              <BackgroundMap />
            </div>
            <Signature />
          </div>
          <About />
        </div>
      </main>
    </>
  );
};

export default Home;
